[package]
name = "app-launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
dirs = "6.0.0"
walkdir = "2.5.0"
rust-ini = "0.21.3"
linicon = "2.3.0"
